postgresql:
  image: sameersbn/postgresql:9.4-1
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabdb
#  volumes:
#    - /Users/jmiddleton/Documents/tmp/postgresql:/var/lib/postgresql
gitlab:
  image: sameersbn/gitlab:7.12.0
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - TZ=Australia\/Sydney
    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login
    - GITLAB_TIMEZONE=Sydney
    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_EMAIL=admin@example.com
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=01:00
  volumes:
    - /Users/jmiddleton/Documents/tmp/gitlab/gitlab:/home/git/data
redis:
  image: sameersbn/redis:latest
  volumes:
    - /Users/jmiddleton/Documents/tmp/gitlab/redis:/var/lib/redis
artifactory:
  image: jfrog-docker-registry.bintray.io/artifactory/artifactory-oss:latest
  ports:
    - "38081:8081"
    - "30080:80"
jenkins:
  image: jenkins
  environment:
    - JENKINS_HOME=/var/jenkins_home
  ports:
    - "32768:8080"
    - "32769:50000"
  volumes:
    - /Users/jmiddleton/Documents/tmp/jenkins/var/jenkins_home:/var/jenkins_home
registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
#    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
#    REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
  volumes:
    - /Users/jmiddleton/Documents/tmp/myregistrydata:/var/lib/registry
sonarqube:
  image: sonarqube:latest
  links:
    - dbsonar:db
  environment:
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
    - SONARQUBE_JDBC_URL=jdbc:postgresql://192.168.59.103:45432/sonar
  ports:
    - "49000:9000"
dbsonar:
  image: postgres
  environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
  ports:
    - "45432:5432"
  volumes:
    - /Users/jmiddleton/Documents/tmp/sonarpostgresql:/var/lib/postgresql
